### ISSUE TITLE
Fcntl not working on Windows 10

### ISSUE THREAD

**Issue by josevjunior** [baudehlo/node-fs-ext#100]
I cannot use ```fcntl``` or ```fcntlSync```. When I call that functions, this exception is throw: 

```
TypeError: binding.fcntl is not a function
    at exports.fcntlSync (C:\Users\Jose\Documents\Git\node-test\node_modules\fs-ext\fs-ext.js:112:18)
    at Object.<anonymous> (C:\Users\Jose\Documents\Git\node-test\src\main.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

What is the problem?

My enviroment:
 - Windows 10
 - Node v14.15.3
 - NPM 6.14.9

**Comment by dalduba** [comment]
Confirm the issue:

- Windows 10
- Node v16.14.0
- NPM 8.3.1
