### ISSUE TITLE
Cannot install, compile error

### ISSUE THREAD

**Issue by rogierschouten** [baudehlo/node-fs-ext#44]
I can't install fs-ext due to the compile error below. I have Windows 7, VS2013, Node 0.10.36 and NPM 2.6.0.

```
c:\Source\node-splogger\spirit-logger-file\node_modules\fs-ext>node "c:\Users\rogiers\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fs-ext.cc
..\fs-ext.cc(195): error C3861: 'fcntl': identifier not found [c:\Source\node-splogger\spirit-logger-file\node_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(379): error C3861: 'fcntl': identifier not found [c:\Source\node-splogger\spirit-logger-file\node_modules\fs-ext\build\fs-ext.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Users\rogiers\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Users\\rogiers\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd c:\Source\node-splogger\spirit-logger-file\node_modules\fs-ext
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\rogiers\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "fs-ext"
npm ERR! node v0.10.36
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! fs-ext@0.4.4 install: `node-gyp configure build`
npm ERR! Exit status 1

```

**Comment by eranimo** [comment]
I'm getting this too on the latest version of node. Did you fix it?

**Comment by rogierschouten** [comment]
No sorry found no solution.

**Comment by eranimo** [comment]
I ended up having to stop using this plugin and like 4 others that use it. It's a shame.

**Comment by timdp** [comment]
What happened here? It used to work according to #24.

**Comment by ashwanikumar04** [comment]
Is this issue fixed. I am also getting the same issue.

**Comment by gregarndt** [comment]
Just checking in to see if anyone has found a solution to this yet.  I just tried it on a Windows Server 2016 TP2 box and received the same errors.  Using node 0.12.4.

**Comment by Programming4life** [comment]
+1 Almost every module I try and install depends on this module please fix it.

**Comment by dzilbers** [comment]
It looks like fs-ext is an optional dependency for most of npm modules (e.g. mosca) and they should work without it as well. Chek with modules' authors

**Comment by baudehlo** [comment]
Should be fixed.
