### ISSUE TITLE
error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’

### ISSUE THREAD

**Issue by osmoma** [baudehlo/node-fs-ext#56]
EDIT:  The bug of "REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’" is explained here:
https://github.com/fivdi/onoff/wiki/Node.js-v0.10.29-and-native-addons-on-the-Raspberry-Pi

Bug report:
I want to install fs-ext on Raspberry Pi2 with Rasbian distro.
The npm command returns: npm ERR! not OK code 0.
I could not find any npm-debug.log file.

I have these program versions:
$ npm --version
1.4.21

$ nodejs --version 
v0.10.29

$ g++ --version
g++ (Raspbian 4.9.2-10) 4.9.2

$ lsb_release -a
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie) for Raspberry Pi.
## Release:    8.0  Codename: jessie

$ npm install fs-ext 

> fs-ext@0.5.0 install /home/pi/node_modules/fs-ext
> node-gyp configure build

make: Entering directory '/home/pi/node_modules/fs-ext/build'
  CXX(target) Release/obj.target/fs-ext/fs-ext.o
In file included from ../fs-ext.cc:27:0:
../node_modules/nan/nan.h:328:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
../fs-ext.cc: In function ‘void EIO_After(uv_work_t_)’:
../fs-ext.cc:108:20: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     argv[0] = Nan::NanErrnoException(store_data->error);
                    ^
../fs-ext.cc:108:55: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     argv[0] = Nan::NanErrnoException(store_data->error);
                                                       ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flock(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:297:45: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (i != 0) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                             ^
../fs-ext.cc:297:68: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (i != 0) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                                    ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Seek(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:339:56: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (offs_result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                        ^
../fs-ext.cc:339:79: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (offs_result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                                               ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Fcntl(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:375:51: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                   ^
../fs-ext.cc:375:74: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                                          ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE UTime(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:433:47: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "utime", "", _path));
                                               ^
../fs-ext.cc:433:90: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "utime", "", _path));
                                                                                          ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE StatVFS(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:469:47: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "statvfs", "", _path));
                                               ^
../fs-ext.cc:469:92: warning: ‘v8::Localv8::Value Nan::NanErrnoException(int, const char_, const char_, const char_)’ is deprecated (declared at ../node_modules/nan/nan.h:1184) [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "statvfs", "", _path));
                                                                                            ^
fs-ext.target.mk:82: recipe for target 'Release/obj.target/fs-ext/fs-ext.o' failed
make: *_\* [Release/obj.target/fs-ext/fs-ext.o] Error 1
make: Leaving directory '/home/pi/node_modules/fs-ext/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/pi/node_modules/fs-ext
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! fs-ext@0.5.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fs-ext@0.5.0 install script.
npm ERR! This is most likely a problem with the fs-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fs-ext
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.13-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "fs-ext"
npm ERR! cwd /home/pi/irrman
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/irrman/npm-debug.log
## npm ERR! not ok code 0

Fs-ext installed fine on Ubuntu 15.10 and now I want to move the code to Raspberry Pi2 that runs Rasbian/Debian distro.  I have already NPM'ed various Node modules with success, like; express, wiring-pi, watch, workerjs, semaphore and death.

**Comment by osmoma** [comment]
This bug with  "REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’" is explained here:
https://github.com/fivdi/onoff/wiki/Node.js-v0.10.29-and-native-addons-on-the-Raspberry-Pi
