### ISSUE TITLE
I couldn't install fs-ext

### ISSUE THREAD

**Issue by benxiaohailingjun** [baudehlo/node-fs-ext#58]
I couldn't install fs-ext in  windows,when I get the error 
gyp ERR! build error
gyp ERR! stack Error: ENOENT, open 'C:\Users\Administrator.node-gyp\0.10.26\x64
\node.lib'
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "configure" "build"
gyp ERR! cwd D:\Users\paopao\workspace\viewer\node_modules\fs-ext
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! fs-ext@0.3.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
And when I copy the fs-ext form centos I get the error:
 Error: %1 is not a valid Win32 application
I know that npm is download  The Source Code and use gyp complie .
why I complie it failed

**Comment by blunt1337** [comment]
Same here.

**Comment by fabianfrz** [comment]
Having the same error with 

```
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
```

with version 0.5.0 of the library

**Comment by fabianfrz** [comment]
Output of npm:
```
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "bugs" "fs-ext"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path xdg-open
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn xdg-open

npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

Output of npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'bugs', 'fs-ext' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 silly fetchPackageMetaData fs-ext
6 silly fetchNamedPackageData fs-ext
7 silly mapToRegistry name fs-ext
8 silly mapToRegistry using default registry
9 silly mapToRegistry registry https://registry.npmjs.org/
10 silly mapToRegistry data Result {
10 silly mapToRegistry   raw: 'fs-ext',
10 silly mapToRegistry   scope: null,
10 silly mapToRegistry   escapedName: 'fs-ext',
10 silly mapToRegistry   name: 'fs-ext',
10 silly mapToRegistry   rawSpec: '',
10 silly mapToRegistry   spec: 'latest',
10 silly mapToRegistry   type: 'tag' }
11 silly mapToRegistry uri https://registry.npmjs.org/fs-ext
12 verbose request uri https://registry.npmjs.org/fs-ext
13 verbose request no auth needed
14 info attempt registry request try #1 at 07:24:33
15 verbose request id 375cebc610ea434f
16 verbose etag W/"561fdb3c-48d7"
17 http request GET https://registry.npmjs.org/fs-ext
18 http 200 https://registry.npmjs.org/fs-ext
19 verbose headers { server: 'nginx/1.10.1',
19 verbose headers   'content-type': 'application/json',
19 verbose headers   'last-modified': 'Tue, 06 Dec 2016 10:25:33 GMT',
19 verbose headers   etag: 'W/"5846921d-48b6"',
19 verbose headers   'cache-control': 'max-age=300',
19 verbose headers   'content-length': '2985',
19 verbose headers   'accept-ranges': 'bytes',
19 verbose headers   date: 'Wed, 07 Dec 2016 06:24:36 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   'x-served-by': 'cache-ams4141-AMS',
19 verbose headers   'x-cache': 'MISS',
19 verbose headers   'x-cache-hits': '0',
19 verbose headers   'x-timer': 'S1481091876.365666,VS0,VE7',
19 verbose headers   vary: 'Accept-Encoding',
19 verbose headers   connection: 'close',
19 verbose headers   'content-encoding': 'gzip',
19 verbose headers   age: '0' }
20 silly get cb [ 200,
20 silly get   { server: 'nginx/1.10.1',
20 silly get     'content-type': 'application/json',
20 silly get     'last-modified': 'Tue, 06 Dec 2016 10:25:33 GMT',
20 silly get     etag: 'W/"5846921d-48b6"',
20 silly get     'cache-control': 'max-age=300',
20 silly get     'content-length': '2985',
20 silly get     'accept-ranges': 'bytes',
20 silly get     date: 'Wed, 07 Dec 2016 06:24:36 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     'x-served-by': 'cache-ams4141-AMS',
20 silly get     'x-cache': 'MISS',
20 silly get     'x-cache-hits': '0',
20 silly get     'x-timer': 'S1481091876.365666,VS0,VE7',
20 silly get     vary: 'Accept-Encoding',
20 silly get     connection: 'close',
20 silly get     'content-encoding': 'gzip',
20 silly get     age: '0' } ]
21 verbose get saving fs-ext to /root/.npm/registry.npmjs.org/fs-ext/.cache.json
22 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
23 silly bugs url https://github.com/baudehlo/node-fs-ext/issues
24 verbose stack Error: spawn xdg-open ENOENT
24 verbose stack     at exports._errnoException (util.js:1026:11)
24 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
24 verbose stack     at onErrorNT (internal/child_process.js:359:16)
24 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
24 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
25 verbose cwd /root
26 error Linux 3.16.0-4-amd64
27 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "bugs" "fs-ext"
28 error node v6.9.1
29 error npm  v3.10.8
30 error path xdg-open
31 error code ENOENT
32 error errno ENOENT
33 error syscall spawn xdg-open
34 error enoent spawn xdg-open ENOENT
35 error enoent spawn xdg-open ENOENT
35 error enoent This is most likely not a problem with npm itself
35 error enoent and is related to npm not being able to find a file.
36 verbose exit [ 1, true ]
```

**Comment by davedoesdev** [comment]
Fixed by https://github.com/baudehlo/node-fs-ext/pull/70
