### ISSUE TITLE
Error installing fs-ext 1.1.0

### ISSUE THREAD

**Issue by martinwin** [baudehlo/node-fs-ext#74]
When I try to install 1.1.0 I get
```
> fs-ext@1.1.0 install /Users/martin/Projects/sitar-client-js/node_modules/fs-ext
> node-gyp configure build

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/fs-ext/fs-ext.o
../fs-ext.cc:156:40: error: too few arguments to function call, expected 4, have 3
  Nan::Call(*store_data->cb, argc, argv);
  ~~~~~~~~~                            ^
../../nan/nan_maybe_43_inl.h:326:1: note: 'Call' declared here
inline MaybeLocal<v8::Value> Call(
^
1 error generated.
make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/martin/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/martin/.nvm/versions/node/v8.9.1/bin/node" "/Users/martin/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/martin/Projects/sitar-client-js/node_modules/fs-ext
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fs-ext@1.1.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fs-ext@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/martin/.npm/_logs/2018-06-14T21_05_56_029Z-debug.log```

**Comment by baudehlo** [comment]
Pretty sure this was fixed by #73 

Just published 1.2.0. Try it. Closing, but re-open if it's still a problem.

**Comment by martinwin** [comment]
Now fails with 
```
> fs-ext@1.2.0 install /Users/martin/Projects/sitar-client-js/node_modules/fs-ext
> node-gyp configure build

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/fs-ext/fs-ext.o
../fs-ext.cc:156:21: error: expected ';' after expression
  Nan::AsyncResource async_resource("fs-ext:EIO_After");
                    ^
                    ;
../fs-ext.cc:156:8: error: no member named 'AsyncResource' in namespace 'Nan'
  Nan::AsyncResource async_resource("fs-ext:EIO_After");
  ~~~~~^
../fs-ext.cc:156:22: error: use of undeclared identifier 'async_resource'
  Nan::AsyncResource async_resource("fs-ext:EIO_After");
                     ^
../fs-ext.cc:157:37: error: use of undeclared identifier 'async_resource'
  store_data->cb->Call(argc, argv, &async_resource);
                                    ^
4 errors generated.
make: *** [Release/obj.target/fs-ext/fs-ext.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/martin/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/martin/.nvm/versions/node/v8.9.1/bin/node" "/Users/martin/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/martin/Projects/sitar-client-js/node_modules/fs-ext
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fs-ext@1.2.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fs-ext@1.2.0 install script.
```

**Comment by baudehlo** [comment]
@davedoesdev - can you help with this one?

**Comment by davedoesdev** [comment]
@martinwin what if you just do

`npm install fs-ext`

from the command line?

**Comment by davedoesdev** [comment]
@baudehlo I'm wondering if the `nan` depedency needs to be updated in `package.json` so it demands the latest version?

**Comment by davedoesdev** [comment]
https://github.com/baudehlo/node-fs-ext/pull/75 for dependency update

**Comment by martinwin** [comment]
@davedoesdev yes it works if I only install fs-ext but not if I npm install. I do have something else using nan, so I hope your change will fix it.

**Comment by davedoesdev** [comment]
@martinwin what if you temporarily change your dependency to `"@davedoesdev/fs-ext": "~1.2.1"`

I've published that with my change.

**Comment by martinwin** [comment]
@davedoesdev, that's working great for me. Thanks!

**Comment by davedoesdev** [comment]
Cool - thanks for trying it. Once #75 is merged and a new version published we can stop using the scoped package.
